[mypy]
python_version = 3.11
strict = false
ignore_missing_imports = true
warn_return_any = false
warn_unused_ignores = false

[mypy-dask.*]
ignore_missing_imports = true

[mypy-bokeh.*]
ignore_missing_imports = true
